# <center>Iris Flower Project

## Project Scope
**Overall Goal** - Can the physical measurements of Iris flowers help us understand the differences between the three Iris species present in the dataset

*Objectives:*
1. Which species has the largest average petal length?
2. Which measurements are most strongly correlated?
3. How do the distributions differ between species?
4. Can you visualize the species using scatter plots?
5. Can a simple classification model predict the species?

In [ ]:
# relevant libraries
import pandas as pd

## Loading and Inspecting the Data

In [4]:
# loading the dataset
df = pd.read_csv("IRIS.csv")
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
# preliminary data analysis
df.info() # concise technical summary of the dataframe###########dndneo####dfscwwdwfwlcxwdwwdwdwdwdwdq  qdDWDVDVF

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [ ]:
df.describe() # gives summary statistics on the entire dataset

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
df.head(10) # shows the first 10 values in the dataset

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [ ]:
df.isnull().sum() # outlines if there are any missing values

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
df.columns # identifies the columns present

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [ ]:
df.shape # identifies the rows and columns in the dataset

(150, 5)

In [ ]:
df.duplicated().sum() #count the total number of duplicate rows in a dataframe

3

In [ ]:
df.drop_duplicates() # removes identical rows, keeps the first occurrence

#variations on the syntax
# df.drop_duplicates(inplace=True) - modifies the original dataframe instead of creating a copy
# by specific columns: df.drop_duplicates(subset=['col1', 'col2'])
# keep the last occurrence: df.drop_duplicates(keep='last')
# remove all copies entirely: df.drop_duplicates(keep'False)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[147 rows x 5 columns]

In [24]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [ ]:
df['species'].unique() # returns an array of all the distinct, 
# non-repeating values inside the 'species' column

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

## Exploratory Data Analysis

### **Question 1:**  How many flowers belong to each species

In [30]:
df.value_counts()

sepal_length  sepal_width  petal_length  petal_width  species
4.9           3.1          1.5           0.1          Iris-setosa        3
5.8           2.7          5.1           1.9          Iris-virginica     2
              4.0          1.2           0.2          Iris-setosa        1
5.9           3.0          4.2           1.5          Iris-versicolor    1
6.2           3.4          5.4           2.3          Iris-virginica     1
                                                                        ..
5.5           2.3          4.0           1.3          Iris-versicolor    1
              2.4          3.7           1.0          Iris-versicolor    1
                           3.8           1.1          Iris-versicolor    1
              2.5          4.0           1.3          Iris-versicolor    1
7.9           3.8          6.4           2.0          Iris-virginica     1
Name: count, Length: 147, dtype: int64

In [27]:
df['species'].value_counts()

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [32]:
df[['species', 'sepal_length']].value_counts()

species          sepal_length
Iris-setosa      5.0             8
                 5.1             8
Iris-virginica   6.3             6
Iris-versicolor  5.5             5
Iris-virginica   6.7             5
Iris-setosa      5.4             5
Iris-versicolor  5.6             5
Iris-virginica   6.4             5
Iris-setosa      4.8             5
Iris-versicolor  5.7             5
Iris-setosa      4.9             4
Iris-virginica   6.5             4
Iris-setosa      4.6             4
Iris-virginica   7.7             4
Iris-versicolor  6.1             4
                 6.0             4
                 6.7             3
Iris-setosa      4.4             3
Iris-versicolor  5.8             3
                 6.3             3
Iris-virginica   5.8             3
                 6.9             3
                 7.2             3
Iris-setosa      5.2             3
Iris-virginica   6.1             2
                 6.2             2
Iris-setosa      4.7             2
                 5.5             2
                 5.7             2
Iris-versicolor  6.6             2
Iris-virginica   6.0             2
Iris-versicolor  6.4             2
                 6.2             2
                 5.0             2
                 5.9             2
Iris-virginica   6.8             2
                 7.4             1
                 7.6             1
                 7.3             1
                 7.1             1
Iris-setosa      4.3             1
Iris-virginica   5.9             1
                 5.7             1
                 5.6             1
                 4.9             1
Iris-versicolor  7.0             1
                 6.9             1
                 6.8             1
                 6.5             1
                 5.4             1
                 5.2             1
                 5.1             1
                 4.9             1
Iris-setosa      5.8             1
                 5.3             1
                 4.5             1
Iris-virginica   7.9             1
Name: count, dtype: int64

### **Question 2:**  What are the average measurements for each species?

In [ ]:
df.groupby('species').mean()
# splits your DataFrame into groups based on a specific column 
# so you can perform calculations (like sum, average, or count) 
# on each group separately.

                 sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa             5.006        3.418         1.464        0.244
Iris-versicolor         5.936        2.770         4.260        1.326
Iris-virginica          6.588        2.974         5.552        2.026

In [39]:
df.groupby('species')['sepal_length'].mean()

species
Iris-setosa        5.006
Iris-versicolor    5.936
Iris-virginica     6.588
Name: sepal_length, dtype: float64

In [40]:
df.groupby('species')['sepal_length'].agg(['mean', 'min', 'max'])

                  mean  min  max
species
Iris-setosa      5.006  4.3  5.8
Iris-versicolor  5.936  4.9  7.0
Iris-virginica   6.588  4.9  7.9

### **Question 3:**  How do the measurements vary?